version: "3.4"
services:
api:
   build: ./ContosoTraders.Ui.Website/
   app id: 9b0aa6b7-39bd-44e5-a137-1702c1976e20
   app secret: i1R8Q~Hn8dHn86VlWE7xJtLR4FKTIcQBXcebqcv4
web:
   build: ./ContosoTraders.Api.Products
